const TestTransactions = [
  {
    id: "aaa",
    date: "2022-01-06",
    type: "expense",
    category: "shopping",
    description: "Shopee",
    amount: "515",
    paymentMethod: "card",
    cardNum: "1111",
    rewardsCat: "online",
  },
  {
    id: "bbb",
    date: "2022-01-06",
    type: "expense",
    category: "transport",
    description: "mrt",
    amount: "20",
    paymentMethod: "card",
    cardNum: "1111",
    rewardsCat: "green",
  },
  {
    id: "ccc",
    date: "2022-01-01",
    type: "expense",
    category: "food",
    description: "Don Don Donki",
    amount: "45",
    paymentMethod: "card",
    cardNum: "1111",
    rewardsCat: "others",
  },
  {
    id: "ddd",
    date: "2022-01-01",
    type: "expense",
    category: "food",
    description: "Hai Di Lao",
    amount: "100",
    paymentMethod: "cash",
    cardNum: null,
    rewardsCat: null,
  },
  {
    id: "eee",
    date: "2021-01-01",
    type: "expense",
    category: "food",
    description: "Hai Di Lao",
    amount: "100",
    paymentMethod: "card",
    cardNum: "1111",
    rewardsCat: "paywave",
  },
  {
    id: "fff",
    date: "2022-01-01",
    type: "expense",
    category: "food",
    description: "Hai Di Lao",
    amount: "50",
    paymentMethod: "card",
    cardNum: "1111",
    rewardsCat: "paywave",
  },
  {
    id: "ggg",
    date: "2022-01-25",
    type: "expense",
    category: "sports",
    description: "Nike Shoes",
    amount: "180",
    paymentMethod: "card",
    cardNum: "2222",
    rewardsCat: "all",
  },
  {
    id: "hhh",
    date: "2022-01-30",
    type: "expense",
    category: "transport",
    description: "Grab",
    amount: "25",
    paymentMethod: "cash",
    cardNum: null,
    rewardsCat: null,
  },
  {
    id: "iii",
    date: "2022-01-30",
    type: "expense",
    category: "food",
    description: "Grab Food",
    amount: "25",
    paymentMethod: "cash",
    cardNum: null,
    rewardsCat: null,
  },
  {
    id: "jjj",
    date: "2022-05-01",
    type: "expense",
    category: "food",
    description: "Hai Di Lao",
    amount: "50",
    paymentMethod: "card",
    cardNum: "1111",
    rewardsCat: "paywave",
  },
  {
    id: "kkk",
    date: "2022-02-01",
    type: "expense",
    category: "food",
    description: "Hai Di Lao",
    amount: "50",
    paymentMethod: "card",
    cardNum: "1111",
    rewardsCat: "paywave",
  },
  {
    id: "lll",
    date: "2022-03-01",
    type: "expense",
    category: "food",
    description: "Hai Di Lao",
    amount: "50",
    paymentMethod: "card",
    cardNum: "1111",
    rewardsCat: "paywave",
  },
  {
    id: "mmm",
    date: "2022-04-01",
    type: "expense",
    category: "food",
    description: "Hai Di Lao",
    amount: "50",
    paymentMethod: "card",
    cardNum: "1111",
    rewardsCat: "paywave",
  },
  {
    id: "nnn",
    date: "2022-05-01",
    type: "expense",
    category: "sports",
    description: "Fitness First",
    amount: "192",
    paymentMethod: "card",
    cardNum: "1111",
    rewardsCat: "online",
  },
  {
    id: "ooo",
    date: "2022-01-01",
    type: "income",
    category: "salary",
    description: "salary",
    amount: "2000",
    paymentMethod: "cash",
    cardNum: null,
    rewardsCat: null,
  },
  {
    id: "ppp",
    date: "2022-02-25",
    type: "expense",
    category: "sports",
    description: "Puma Shoes",
    amount: "100",
    paymentMethod: "card",
    cardNum: "2222",
    rewardsCat: "all",
  },
  {
    id: "qqq",
    date: "2022-12-01",
    type: "expense",
    category: "sports",
    description: "Fitness First",
    amount: "192",
    paymentMethod: "card",
    cardNum: "1111",
    rewardsCat: "online",
  },
  {
    id: "rrr",
    date: "2022-06-01",
    type: "expense",
    category: "sports",
    description: "Fitness First",
    amount: "116",
    paymentMethod: "card",
    cardNum: "1111",
    rewardsCat: "online",
  },
  {
    id: "sss",
    date: "2022-07-01",
    type: "expense",
    category: "sports",
    description: "Fitness First",
    amount: "99",
    paymentMethod: "card",
    cardNum: "1111",
    rewardsCat: "online",
  },
  {
    id: "ttt",
    date: "2022-07-01",
    type: "expense",
    category: "others",
    description: "Gift",
    amount: "500",
    paymentMethod: "card",
    cardNum: "1111",
    rewardsCat: "online",
  },
];

export default TestTransactions;
